POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "leo",
  "email": "leo@gmail.com",
  "referrerId": "c4965c95-853d-499a-bd16-99b3828dc625"
}

###

GET http://localhost:3333/invites/00318065-732e-4d30-bb71-bc6258466edb

###

GET http://localhost:3333/subscribers/00318065-732e-4d30-bb71-bc6258466edb/ranking/clicks

###

GET http://localhost:3333/subscribers/00318065-732e-4d30-bb71-bc6258466edb/ranking/count

### 

GET http://localhost:3333/subscribers/00318065-732e-4d30-bb71-bc6258466edb/ranking/position

### 

GET http://localhost:3333/ranking